// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFetchHistory(arg1) {
  return window['go']['main']['App']['AddFetchHistory'](arg1);
}

export function AddToDownloadQueue(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddToDownloadQueue'](arg1, arg2, arg3, arg4);
}

export function AddTracksToPlaylist(arg1, arg2) {
  return window['go']['main']['App']['AddTracksToPlaylist'](arg1, arg2);
}

export function ApplyUpdate(arg1) {
  return window['go']['main']['App']['ApplyUpdate'](arg1);
}

export function CancelAllQueuedItems() {
  return window['go']['main']['App']['CancelAllQueuedItems']();
}

export function CheckAPIStatus(arg1, arg2) {
  return window['go']['main']['App']['CheckAPIStatus'](arg1, arg2);
}

export function CheckAPIStatusReport(arg1, arg2) {
  return window['go']['main']['App']['CheckAPIStatusReport'](arg1, arg2);
}

export function CheckCustomQobuzAPI(arg1) {
  return window['go']['main']['App']['CheckCustomQobuzAPI'](arg1);
}

export function CheckCustomTidalAPI(arg1) {
  return window['go']['main']['App']['CheckCustomTidalAPI'](arg1);
}

export function CheckFFmpegInstalled() {
  return window['go']['main']['App']['CheckFFmpegInstalled']();
}

export function CheckFilesExistence(arg1, arg2, arg3) {
  return window['go']['main']['App']['CheckFilesExistence'](arg1, arg2, arg3);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckTrackAvailability(arg1) {
  return window['go']['main']['App']['CheckTrackAvailability'](arg1);
}

export function ClearAllDownloads() {
  return window['go']['main']['App']['ClearAllDownloads']();
}

export function ClearCompletedDownloads() {
  return window['go']['main']['App']['ClearCompletedDownloads']();
}

export function ClearDownloadHistory() {
  return window['go']['main']['App']['ClearDownloadHistory']();
}

export function ClearFetchHistory() {
  return window['go']['main']['App']['ClearFetchHistory']();
}

export function ClearFetchHistoryByType(arg1) {
  return window['go']['main']['App']['ClearFetchHistoryByType'](arg1);
}

export function ConvertAudio(arg1) {
  return window['go']['main']['App']['ConvertAudio'](arg1);
}

export function CreateLogFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateLogFile'](arg1, arg2, arg3);
}

export function CreateM3U8File(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateM3U8File'](arg1, arg2, arg3);
}

export function CreatePlaylist(arg1) {
  return window['go']['main']['App']['CreatePlaylist'](arg1);
}

export function DecodeAudioForAnalysis(arg1) {
  return window['go']['main']['App']['DecodeAudioForAnalysis'](arg1);
}

export function DeleteDownloadHistoryItem(arg1) {
  return window['go']['main']['App']['DeleteDownloadHistoryItem'](arg1);
}

export function DeleteFetchHistoryItem(arg1) {
  return window['go']['main']['App']['DeleteFetchHistoryItem'](arg1);
}

export function DeleteLibraryTracks(arg1) {
  return window['go']['main']['App']['DeleteLibraryTracks'](arg1);
}

export function DeletePlaylist(arg1) {
  return window['go']['main']['App']['DeletePlaylist'](arg1);
}

export function DownloadAvatar(arg1) {
  return window['go']['main']['App']['DownloadAvatar'](arg1);
}

export function DownloadCover(arg1) {
  return window['go']['main']['App']['DownloadCover'](arg1);
}

export function DownloadFFmpeg() {
  return window['go']['main']['App']['DownloadFFmpeg']();
}

export function DownloadGalleryImage(arg1) {
  return window['go']['main']['App']['DownloadGalleryImage'](arg1);
}

export function DownloadHeader(arg1) {
  return window['go']['main']['App']['DownloadHeader'](arg1);
}

export function DownloadLyrics(arg1) {
  return window['go']['main']['App']['DownloadLyrics'](arg1);
}

export function DownloadLyricsForFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DownloadLyricsForFile'](arg1, arg2, arg3, arg4, arg5);
}

export function DownloadTrack(arg1) {
  return window['go']['main']['App']['DownloadTrack'](arg1);
}

export function EmbedCoverFromSource(arg1, arg2) {
  return window['go']['main']['App']['EmbedCoverFromSource'](arg1, arg2);
}

export function EnqueueDownload(arg1) {
  return window['go']['main']['App']['EnqueueDownload'](arg1);
}

export function EnrichLibraryArtist(arg1) {
  return window['go']['main']['App']['EnrichLibraryArtist'](arg1);
}

export function EnsureLibraryFolder(arg1) {
  return window['go']['main']['App']['EnsureLibraryFolder'](arg1);
}

export function ExportFailedDownloads() {
  return window['go']['main']['App']['ExportFailedDownloads']();
}

export function ExtractLyricsToLRC(arg1, arg2) {
  return window['go']['main']['App']['ExtractLyricsToLRC'](arg1, arg2);
}

export function FetchKazooStatusPayload(arg1) {
  return window['go']['main']['App']['FetchKazooStatusPayload'](arg1);
}

export function FindLibraryAlbum(arg1, arg2) {
  return window['go']['main']['App']['FindLibraryAlbum'](arg1, arg2);
}

export function FindLibraryArtistName(arg1) {
  return window['go']['main']['App']['FindLibraryArtistName'](arg1);
}

export function ForceStopDownloads() {
  return window['go']['main']['App']['ForceStopDownloads']();
}

export function GetAlbumArtCandidates(arg1, arg2) {
  return window['go']['main']['App']['GetAlbumArtCandidates'](arg1, arg2);
}

export function GetAlbumTracks(arg1) {
  return window['go']['main']['App']['GetAlbumTracks'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetArtistAlbums(arg1) {
  return window['go']['main']['App']['GetArtistAlbums'](arg1);
}

export function GetArtistArtCandidates(arg1) {
  return window['go']['main']['App']['GetArtistArtCandidates'](arg1);
}

export function GetArtistBanner(arg1) {
  return window['go']['main']['App']['GetArtistBanner'](arg1);
}

export function GetArtistImage(arg1) {
  return window['go']['main']['App']['GetArtistImage'](arg1);
}

export function GetArtistLocks(arg1) {
  return window['go']['main']['App']['GetArtistLocks'](arg1);
}

export function GetArtistMeta(arg1) {
  return window['go']['main']['App']['GetArtistMeta'](arg1);
}

export function GetArtistNewReleases(arg1) {
  return window['go']['main']['App']['GetArtistNewReleases'](arg1);
}

export function GetArtistReleases(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetArtistReleases'](arg1, arg2, arg3);
}

export function GetArtistSpotifyPlaylists(arg1) {
  return window['go']['main']['App']['GetArtistSpotifyPlaylists'](arg1);
}

export function GetArtistTopTracks(arg1) {
  return window['go']['main']['App']['GetArtistTopTracks'](arg1);
}

export function GetBestAlbumQualitiesByID(arg1) {
  return window['go']['main']['App']['GetBestAlbumQualitiesByID'](arg1);
}

export function GetBestTrackQualities(arg1) {
  return window['go']['main']['App']['GetBestTrackQualities'](arg1);
}

export function GetBestTrackQuality(arg1) {
  return window['go']['main']['App']['GetBestTrackQuality'](arg1);
}

export function GetBrewPath() {
  return window['go']['main']['App']['GetBrewPath']();
}

export function GetCommonMetadata(arg1) {
  return window['go']['main']['App']['GetCommonMetadata'](arg1);
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetCurrentIPInfo() {
  return window['go']['main']['App']['GetCurrentIPInfo']();
}

export function GetDefaults() {
  return window['go']['main']['App']['GetDefaults']();
}

export function GetDownloadHistory() {
  return window['go']['main']['App']['GetDownloadHistory']();
}

export function GetDownloadProgress() {
  return window['go']['main']['App']['GetDownloadProgress']();
}

export function GetDownloadQueue() {
  return window['go']['main']['App']['GetDownloadQueue']();
}

export function GetDownloadQueueCounts() {
  return window['go']['main']['App']['GetDownloadQueueCounts']();
}

export function GetEditableMetadata(arg1) {
  return window['go']['main']['App']['GetEditableMetadata'](arg1);
}

export function GetEmbeddedCover(arg1) {
  return window['go']['main']['App']['GetEmbeddedCover'](arg1);
}

export function GetFetchHistory() {
  return window['go']['main']['App']['GetFetchHistory']();
}

export function GetFileSizes(arg1) {
  return window['go']['main']['App']['GetFileSizes'](arg1);
}

export function GetFlacInfoBatch(arg1) {
  return window['go']['main']['App']['GetFlacInfoBatch'](arg1);
}

export function GetFontsPath() {
  return window['go']['main']['App']['GetFontsPath']();
}

export function GetImageInfo(arg1) {
  return window['go']['main']['App']['GetImageInfo'](arg1);
}

export function GetLibraryAlbumArtists(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetLibraryAlbumArtists'](arg1, arg2, arg3);
}

export function GetLibraryAlbums(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetLibraryAlbums'](arg1, arg2, arg3);
}

export function GetLibraryArtistsList(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetLibraryArtistsList'](arg1, arg2, arg3);
}

export function GetLibraryFacets(arg1) {
  return window['go']['main']['App']['GetLibraryFacets'](arg1);
}

export function GetLibraryFolders() {
  return window['go']['main']['App']['GetLibraryFolders']();
}

export function GetLibraryStats() {
  return window['go']['main']['App']['GetLibraryStats']();
}

export function GetLibraryTracks(arg1) {
  return window['go']['main']['App']['GetLibraryTracks'](arg1);
}

export function GetLibraryTracksByIDs(arg1) {
  return window['go']['main']['App']['GetLibraryTracksByIDs'](arg1);
}

export function GetPlaylistTracks(arg1) {
  return window['go']['main']['App']['GetPlaylistTracks'](arg1);
}

export function GetPlaylists() {
  return window['go']['main']['App']['GetPlaylists']();
}

export function GetPreviewURL(arg1) {
  return window['go']['main']['App']['GetPreviewURL'](arg1);
}

export function GetQobuzArtistDiscography(arg1) {
  return window['go']['main']['App']['GetQobuzArtistDiscography'](arg1);
}

export function GetQueueItemStatus(arg1) {
  return window['go']['main']['App']['GetQueueItemStatus'](arg1);
}

export function GetRecentFetches() {
  return window['go']['main']['App']['GetRecentFetches']();
}

export function GetSpotifyMetadata(arg1) {
  return window['go']['main']['App']['GetSpotifyMetadata'](arg1);
}

export function GetStreamingURLs(arg1, arg2) {
  return window['go']['main']['App']['GetStreamingURLs'](arg1, arg2);
}

export function GetSyncedPlaylistDetail(arg1) {
  return window['go']['main']['App']['GetSyncedPlaylistDetail'](arg1);
}

export function GetTrackAudioInfo(arg1) {
  return window['go']['main']['App']['GetTrackAudioInfo'](arg1);
}

export function GetTrackCredits(arg1) {
  return window['go']['main']['App']['GetTrackCredits'](arg1);
}

export function GetTrackDetails(arg1) {
  return window['go']['main']['App']['GetTrackDetails'](arg1);
}

export function GetTrackISRC(arg1) {
  return window['go']['main']['App']['GetTrackISRC'](arg1);
}

export function GetTrackWaveform(arg1) {
  return window['go']['main']['App']['GetTrackWaveform'](arg1);
}

export function GetUserPlaylists(arg1) {
  return window['go']['main']['App']['GetUserPlaylists'](arg1);
}

export function InstallFFmpegWithBrew() {
  return window['go']['main']['App']['InstallFFmpegWithBrew']();
}

export function IsBrewFFmpegInstalled() {
  return window['go']['main']['App']['IsBrewFFmpegInstalled']();
}

export function IsFFmpegInstalled() {
  return window['go']['main']['App']['IsFFmpegInstalled']();
}

export function IsFFprobeInstalled() {
  return window['go']['main']['App']['IsFFprobeInstalled']();
}

export function ListArtistsNeedingEnrichment() {
  return window['go']['main']['App']['ListArtistsNeedingEnrichment']();
}

export function ListAudioFilesInDir(arg1) {
  return window['go']['main']['App']['ListAudioFilesInDir'](arg1);
}

export function ListDirectoryFiles(arg1) {
  return window['go']['main']['App']['ListDirectoryFiles'](arg1);
}

export function ListSyncedPlaylists() {
  return window['go']['main']['App']['ListSyncedPlaylists']();
}

export function LoadFonts() {
  return window['go']['main']['App']['LoadFonts']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function LockArtistFields(arg1, arg2) {
  return window['go']['main']['App']['LockArtistFields'](arg1, arg2);
}

export function LogStatusConsole(arg1, arg2) {
  return window['go']['main']['App']['LogStatusConsole'](arg1, arg2);
}

export function MarkDownloadItemFailed(arg1, arg2) {
  return window['go']['main']['App']['MarkDownloadItemFailed'](arg1, arg2);
}

export function MatchSpotifyPlaylist(arg1) {
  return window['go']['main']['App']['MatchSpotifyPlaylist'](arg1);
}

export function OpenConfigFolder() {
  return window['go']['main']['App']['OpenConfigFolder']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenSpotifyPlaylist(arg1) {
  return window['go']['main']['App']['OpenSpotifyPlaylist'](arg1);
}

export function PreviewRenameFiles(arg1, arg2) {
  return window['go']['main']['App']['PreviewRenameFiles'](arg1, arg2);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReadEmbeddedLyrics(arg1) {
  return window['go']['main']['App']['ReadEmbeddedLyrics'](arg1);
}

export function ReadFileAsBase64(arg1) {
  return window['go']['main']['App']['ReadFileAsBase64'](arg1);
}

export function ReadFileMetadata(arg1) {
  return window['go']['main']['App']['ReadFileMetadata'](arg1);
}

export function ReadImageAsBase64(arg1) {
  return window['go']['main']['App']['ReadImageAsBase64'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function RefreshArtistMetadata(arg1) {
  return window['go']['main']['App']['RefreshArtistMetadata'](arg1);
}

export function RefreshTrackMetadata(arg1) {
  return window['go']['main']['App']['RefreshTrackMetadata'](arg1);
}

export function RemoveDownloadItems(arg1) {
  return window['go']['main']['App']['RemoveDownloadItems'](arg1);
}

export function RemoveLibraryFolder(arg1) {
  return window['go']['main']['App']['RemoveLibraryFolder'](arg1);
}

export function RemoveMissingLibraryTracks() {
  return window['go']['main']['App']['RemoveMissingLibraryTracks']();
}

export function RemoveSyncedPlaylist(arg1) {
  return window['go']['main']['App']['RemoveSyncedPlaylist'](arg1);
}

export function RemoveTrackFromPlaylist(arg1, arg2) {
  return window['go']['main']['App']['RemoveTrackFromPlaylist'](arg1, arg2);
}

export function RenameFileTo(arg1, arg2) {
  return window['go']['main']['App']['RenameFileTo'](arg1, arg2);
}

export function RenameFilesByMetadata(arg1, arg2) {
  return window['go']['main']['App']['RenameFilesByMetadata'](arg1, arg2);
}

export function RenamePlaylist(arg1, arg2) {
  return window['go']['main']['App']['RenamePlaylist'](arg1, arg2);
}

export function RequeueDownloadItems(arg1) {
  return window['go']['main']['App']['RequeueDownloadItems'](arg1);
}

export function ResampleAudio(arg1) {
  return window['go']['main']['App']['ResampleAudio'](arg1);
}

export function RescanLibrary() {
  return window['go']['main']['App']['RescanLibrary']();
}

export function RescanLibraryQuiet() {
  return window['go']['main']['App']['RescanLibraryQuiet']();
}

export function ResyncSyncedPlaylist(arg1) {
  return window['go']['main']['App']['ResyncSyncedPlaylist'](arg1);
}

export function SaveFonts(arg1) {
  return window['go']['main']['App']['SaveFonts'](arg1);
}

export function SaveLyrics(arg1, arg2) {
  return window['go']['main']['App']['SaveLyrics'](arg1, arg2);
}

export function SaveRecentFetches(arg1) {
  return window['go']['main']['App']['SaveRecentFetches'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveSpectrumImage(arg1, arg2) {
  return window['go']['main']['App']['SaveSpectrumImage'](arg1, arg2);
}

export function ScanLibraryFolder(arg1) {
  return window['go']['main']['App']['ScanLibraryFolder'](arg1);
}

export function ScanLyricsFolder(arg1) {
  return window['go']['main']['App']['ScanLyricsFolder'](arg1);
}

export function SearchArtistMatchCandidates(arg1) {
  return window['go']['main']['App']['SearchArtistMatchCandidates'](arg1);
}

export function SearchQobuzArtists(arg1) {
  return window['go']['main']['App']['SearchQobuzArtists'](arg1);
}

export function SearchQobuzTracks(arg1) {
  return window['go']['main']['App']['SearchQobuzTracks'](arg1);
}

export function SearchSpotify(arg1) {
  return window['go']['main']['App']['SearchSpotify'](arg1);
}

export function SearchSpotifyByType(arg1) {
  return window['go']['main']['App']['SearchSpotifyByType'](arg1);
}

export function SearchSpotifyProfiles(arg1) {
  return window['go']['main']['App']['SearchSpotifyProfiles'](arg1);
}

export function SelectAudioFiles() {
  return window['go']['main']['App']['SelectAudioFiles']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFolder(arg1) {
  return window['go']['main']['App']['SelectFolder'](arg1);
}

export function SelectImageVideo() {
  return window['go']['main']['App']['SelectImageVideo']();
}

export function SelectLyricsFiles() {
  return window['go']['main']['App']['SelectLyricsFiles']();
}

export function SelectLyricsFolder() {
  return window['go']['main']['App']['SelectLyricsFolder']();
}

export function SetArtistBanner(arg1, arg2) {
  return window['go']['main']['App']['SetArtistBanner'](arg1, arg2);
}

export function SetArtistBio(arg1, arg2) {
  return window['go']['main']['App']['SetArtistBio'](arg1, arg2);
}

export function SetArtistImage(arg1, arg2) {
  return window['go']['main']['App']['SetArtistImage'](arg1, arg2);
}

export function SetArtistMatch(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetArtistMatch'](arg1, arg2, arg3);
}

export function SetArtistSpotifyMatch(arg1, arg2) {
  return window['go']['main']['App']['SetArtistSpotifyMatch'](arg1, arg2);
}

export function SetLibraryRating(arg1, arg2) {
  return window['go']['main']['App']['SetLibraryRating'](arg1, arg2);
}

export function SetPlaylistSynced(arg1, arg2) {
  return window['go']['main']['App']['SetPlaylistSynced'](arg1, arg2);
}

export function SetQueuePaused(arg1) {
  return window['go']['main']['App']['SetQueuePaused'](arg1);
}

export function SetTrackMatch(arg1, arg2) {
  return window['go']['main']['App']['SetTrackMatch'](arg1, arg2);
}

export function SkipDownloadItem(arg1, arg2) {
  return window['go']['main']['App']['SkipDownloadItem'](arg1, arg2);
}

export function StartServe(arg1) {
  return window['go']['main']['App']['StartServe'](arg1);
}

export function SyncSpotifyPlaylist(arg1) {
  return window['go']['main']['App']['SyncSpotifyPlaylist'](arg1);
}

export function TrackIDsForAlbums(arg1) {
  return window['go']['main']['App']['TrackIDsForAlbums'](arg1);
}

export function TrackIDsForArtists(arg1) {
  return window['go']['main']['App']['TrackIDsForArtists'](arg1);
}

export function UnlockArtistFields(arg1) {
  return window['go']['main']['App']['UnlockArtistFields'](arg1);
}

export function WriteArtistMetadata(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['WriteArtistMetadata'](arg1, arg2, arg3, arg4);
}

export function WriteBulkTrackMetadata(arg1, arg2) {
  return window['go']['main']['App']['WriteBulkTrackMetadata'](arg1, arg2);
}

export function WriteTrackMetadata(arg1) {
  return window['go']['main']['App']['WriteTrackMetadata'](arg1);
}
