// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {main} from '../models';

export function AddFetchHistory(arg1:backend.FetchHistoryItem):Promise<void>;

export function AddToDownloadQueue(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function AddTracksToPlaylist(arg1:number,arg2:Array<number>):Promise<number>;

export function ApplyUpdate(arg1:string):Promise<string>;

export function CancelAllQueuedItems():Promise<void>;

export function CheckAPIStatus(arg1:string,arg2:string):Promise<boolean>;

export function CheckAPIStatusReport(arg1:string,arg2:string):Promise<main.APIStatusReport>;

export function CheckCustomQobuzAPI(arg1:string):Promise<boolean>;

export function CheckCustomTidalAPI(arg1:string):Promise<boolean>;

export function CheckFFmpegInstalled():Promise<boolean>;

export function CheckFilesExistence(arg1:string,arg2:string,arg3:Array<main.CheckFileExistenceRequest>):Promise<Array<main.CheckFileExistenceResult>>;

export function CheckForUpdate():Promise<backend.UpdateInfo>;

export function CheckTrackAvailability(arg1:string):Promise<string>;

export function ClearAllDownloads():Promise<void>;

export function ClearCompletedDownloads():Promise<void>;

export function ClearDownloadHistory():Promise<void>;

export function ClearFetchHistory():Promise<void>;

export function ClearFetchHistoryByType(arg1:string):Promise<void>;

export function ConvertAudio(arg1:main.ConvertAudioRequest):Promise<Array<backend.ConvertAudioResult>>;

export function CreateLogFile(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function CreateM3U8File(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function CreatePlaylist(arg1:string):Promise<number>;

export function DecodeAudioForAnalysis(arg1:string):Promise<backend.AnalysisDecodeResponse>;

export function DeleteDownloadHistoryItem(arg1:string):Promise<void>;

export function DeleteFetchHistoryItem(arg1:string):Promise<void>;

export function DeleteLibraryTracks(arg1:Array<number>):Promise<number>;

export function DeletePlaylist(arg1:number):Promise<void>;

export function DownloadAvatar(arg1:main.AvatarDownloadRequest):Promise<backend.AvatarDownloadResponse>;

export function DownloadCover(arg1:main.CoverDownloadRequest):Promise<backend.CoverDownloadResponse>;

export function DownloadFFmpeg():Promise<main.DownloadFFmpegResponse>;

export function DownloadGalleryImage(arg1:main.GalleryImageDownloadRequest):Promise<backend.GalleryImageDownloadResponse>;

export function DownloadHeader(arg1:main.HeaderDownloadRequest):Promise<backend.HeaderDownloadResponse>;

export function DownloadLyrics(arg1:main.LyricsDownloadRequest):Promise<backend.LyricsDownloadResponse>;

export function DownloadLyricsForFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<backend.LyricsDownloadResponse>;

export function DownloadTrack(arg1:main.DownloadRequest):Promise<main.DownloadResponse>;

export function EmbedCoverFromSource(arg1:Array<number>,arg2:string):Promise<number>;

export function EnqueueDownload(arg1:backend.DownloadItem):Promise<string>;

export function EnrichLibraryArtist(arg1:string):Promise<backend.EnrichResult>;

export function EnsureLibraryFolder(arg1:string):Promise<boolean>;

export function ExportFailedDownloads():Promise<string>;

export function ExtractLyricsToLRC(arg1:string,arg2:boolean):Promise<backend.ExtractLyricsResult>;

export function FetchKazooStatusPayload(arg1:string):Promise<Record<string, string>>;

export function FindLibraryAlbum(arg1:string,arg2:string):Promise<backend.LibraryAlbum>;

export function FindLibraryArtistName(arg1:string):Promise<string>;

export function ForceStopDownloads():Promise<void>;

export function GetAlbumArtCandidates(arg1:string,arg2:string):Promise<Array<backend.ArtCandidate>>;

export function GetAlbumTracks(arg1:string):Promise<Array<backend.LibraryTrack>>;

export function GetAppVersion():Promise<string>;

export function GetArtistAlbums(arg1:string):Promise<Array<backend.LibraryAlbum>>;

export function GetArtistArtCandidates(arg1:string):Promise<backend.ArtistArtCandidates>;

export function GetArtistBanner(arg1:string):Promise<string>;

export function GetArtistImage(arg1:string):Promise<string>;

export function GetArtistLocks(arg1:string):Promise<Array<string>>;

export function GetArtistMeta(arg1:string):Promise<backend.ArtistMeta>;

export function GetArtistNewReleases(arg1:string):Promise<Array<backend.ArtistReleaseCheck>>;

export function GetArtistReleases(arg1:string,arg2:string,arg3:boolean):Promise<backend.ArtistReleases>;

export function GetArtistSpotifyPlaylists(arg1:string):Promise<Array<backend.ProfilePlaylist>>;

export function GetArtistTopTracks(arg1:string):Promise<Array<backend.ArtistTopTrack>>;

export function GetBestAlbumQualitiesByID(arg1:Array<string>):Promise<Record<string, backend.TrackQuality>>;

export function GetBestTrackQualities(arg1:Array<backend.QualityRequest>):Promise<Record<string, backend.TrackQuality>>;

export function GetBestTrackQuality(arg1:string):Promise<backend.TrackQuality>;

export function GetBrewPath():Promise<string>;

export function GetCommonMetadata(arg1:Array<number>):Promise<backend.CommonMeta>;

export function GetConfigPath():Promise<string>;

export function GetCurrentIPInfo():Promise<string>;

export function GetDefaults():Promise<Record<string, string>>;

export function GetDownloadHistory():Promise<Array<backend.HistoryItem>>;

export function GetDownloadProgress():Promise<backend.ProgressInfo>;

export function GetDownloadQueue():Promise<backend.DownloadQueueInfo>;

export function GetDownloadQueueCounts():Promise<Record<string, number>>;

export function GetEditableMetadata(arg1:string):Promise<backend.TrackMeta>;

export function GetEmbeddedCover(arg1:string):Promise<string>;

export function GetFetchHistory():Promise<Array<backend.FetchHistoryItem>>;

export function GetFileSizes(arg1:Array<string>):Promise<Record<string, number>>;

export function GetFlacInfoBatch(arg1:Array<string>):Promise<Array<backend.FlacInfo>>;

export function GetFontsPath():Promise<string>;

export function GetImageInfo(arg1:string):Promise<backend.ImageInfo>;

export function GetLibraryAlbumArtists(arg1:string,arg2:string,arg3:boolean):Promise<Array<backend.LibraryArtist>>;

export function GetLibraryAlbums(arg1:string,arg2:string,arg3:boolean):Promise<Array<backend.LibraryAlbum>>;

export function GetLibraryArtistsList(arg1:string,arg2:string,arg3:boolean):Promise<Array<backend.LibraryArtist>>;

export function GetLibraryFacets(arg1:string):Promise<Array<backend.Facet>>;

export function GetLibraryFolders():Promise<Array<backend.LibraryFolder>>;

export function GetLibraryStats():Promise<backend.LibStats>;

export function GetLibraryTracks(arg1:backend.LibraryQuery):Promise<Array<backend.LibraryTrack>>;

export function GetLibraryTracksByIDs(arg1:Array<number>):Promise<Array<backend.LibraryTrack>>;

export function GetPlaylistTracks(arg1:number):Promise<Array<backend.LibraryTrack>>;

export function GetPlaylists():Promise<Array<backend.Playlist>>;

export function GetPreviewURL(arg1:string):Promise<string>;

export function GetQobuzArtistDiscography(arg1:string):Promise<string>;

export function GetQueueItemStatus(arg1:string):Promise<string>;

export function GetRecentFetches():Promise<string>;

export function GetSpotifyMetadata(arg1:main.SpotifyMetadataRequest):Promise<string>;

export function GetStreamingURLs(arg1:string,arg2:string):Promise<string>;

export function GetSyncedPlaylistDetail(arg1:number):Promise<backend.SyncedPlaylistDetail>;

export function GetTrackAudioInfo(arg1:number):Promise<backend.TrackAudioInfo>;

export function GetTrackCredits(arg1:string):Promise<Array<backend.Credit>>;

export function GetTrackDetails(arg1:number):Promise<backend.TrackDetails>;

export function GetTrackISRC(arg1:string):Promise<string>;

export function GetTrackWaveform(arg1:number):Promise<Array<number>>;

export function GetUserPlaylists(arg1:string):Promise<Array<backend.ProfilePlaylist>>;

export function InstallFFmpegWithBrew():Promise<main.InstallFFmpegWithBrewResponse>;

export function IsBrewFFmpegInstalled():Promise<boolean>;

export function IsFFmpegInstalled():Promise<boolean>;

export function IsFFprobeInstalled():Promise<boolean>;

export function ListArtistsNeedingEnrichment():Promise<Array<string>>;

export function ListAudioFilesInDir(arg1:string):Promise<Array<backend.FileInfo>>;

export function ListDirectoryFiles(arg1:string):Promise<Array<backend.FileInfo>>;

export function ListSyncedPlaylists():Promise<Array<backend.SyncedPlaylist>>;

export function LoadFonts():Promise<Array<Record<string, any>>>;

export function LoadSettings():Promise<Record<string, any>>;

export function LockArtistFields(arg1:string,arg2:Array<string>):Promise<void>;

export function LogStatusConsole(arg1:string,arg2:string):Promise<void>;

export function MarkDownloadItemFailed(arg1:string,arg2:string):Promise<void>;

export function MatchSpotifyPlaylist(arg1:string):Promise<backend.PlaylistMatchResult>;

export function OpenConfigFolder():Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenSpotifyPlaylist(arg1:string):Promise<backend.SyncedPlaylist>;

export function PreviewRenameFiles(arg1:Array<string>,arg2:string):Promise<Array<backend.RenamePreview>>;

export function Quit():Promise<void>;

export function ReadEmbeddedLyrics(arg1:string):Promise<backend.EmbeddedLyrics>;

export function ReadFileAsBase64(arg1:string):Promise<string>;

export function ReadFileMetadata(arg1:string):Promise<backend.AudioMetadata>;

export function ReadImageAsBase64(arg1:string):Promise<string>;

export function ReadTextFile(arg1:string):Promise<string>;

export function RefreshArtistMetadata(arg1:string):Promise<backend.EnrichResult>;

export function RefreshTrackMetadata(arg1:Array<number>):Promise<number>;

export function RemoveDownloadItems(arg1:Array<string>):Promise<void>;

export function RemoveLibraryFolder(arg1:string):Promise<number>;

export function RemoveMissingLibraryTracks():Promise<number>;

export function RemoveSyncedPlaylist(arg1:number):Promise<void>;

export function RemoveTrackFromPlaylist(arg1:number,arg2:number):Promise<void>;

export function RenameFileTo(arg1:string,arg2:string):Promise<void>;

export function RenameFilesByMetadata(arg1:Array<string>,arg2:string):Promise<Array<backend.RenameResult>>;

export function RenamePlaylist(arg1:number,arg2:string):Promise<void>;

export function RequeueDownloadItems(arg1:Array<string>):Promise<void>;

export function ResampleAudio(arg1:main.ResampleAudioRequest):Promise<Array<backend.ResampleResult>>;

export function RescanLibrary():Promise<backend.ScanResult>;

export function RescanLibraryQuiet():Promise<backend.ScanResult>;

export function ResyncSyncedPlaylist(arg1:number):Promise<backend.SyncedPlaylist>;

export function SaveFonts(arg1:Array<Record<string, any>>):Promise<void>;

export function SaveLyrics(arg1:string,arg2:string):Promise<backend.SaveLyricsResult>;

export function SaveRecentFetches(arg1:string):Promise<void>;

export function SaveSettings(arg1:Record<string, any>):Promise<void>;

export function SaveSpectrumImage(arg1:string,arg2:string):Promise<string>;

export function ScanLibraryFolder(arg1:string):Promise<backend.ScanResult>;

export function ScanLyricsFolder(arg1:string):Promise<Array<string>>;

export function SearchArtistMatchCandidates(arg1:string):Promise<Array<backend.MatchCandidate>>;

export function SearchQobuzArtists(arg1:string):Promise<Array<backend.QobuzArtistHit>>;

export function SearchQobuzTracks(arg1:string):Promise<Array<backend.QobuzSearchTrack>>;

export function SearchSpotify(arg1:main.SpotifySearchRequest):Promise<backend.SearchResponse>;

export function SearchSpotifyByType(arg1:main.SpotifySearchByTypeRequest):Promise<Array<backend.SearchResult>>;

export function SearchSpotifyProfiles(arg1:string):Promise<Array<backend.SpotifyProfile>>;

export function SelectAudioFiles():Promise<Array<string>>;

export function SelectFile():Promise<string>;

export function SelectFolder(arg1:string):Promise<string>;

export function SelectImageVideo():Promise<Array<string>>;

export function SelectLyricsFiles():Promise<Array<string>>;

export function SelectLyricsFolder():Promise<string>;

export function SetArtistBanner(arg1:string,arg2:string):Promise<void>;

export function SetArtistBio(arg1:string,arg2:string):Promise<void>;

export function SetArtistImage(arg1:string,arg2:string):Promise<void>;

export function SetArtistMatch(arg1:string,arg2:string,arg3:string):Promise<backend.EnrichResult>;

export function SetArtistSpotifyMatch(arg1:string,arg2:string):Promise<backend.EnrichResult>;

export function SetLibraryRating(arg1:number,arg2:number):Promise<void>;

export function SetPlaylistSynced(arg1:number,arg2:boolean):Promise<void>;

export function SetQueuePaused(arg1:boolean):Promise<void>;

export function SetTrackMatch(arg1:string,arg2:number):Promise<void>;

export function SkipDownloadItem(arg1:string,arg2:string):Promise<void>;

export function StartServe(arg1:string):Promise<void>;

export function SyncSpotifyPlaylist(arg1:string):Promise<backend.SyncedPlaylist>;

export function TrackIDsForAlbums(arg1:Array<string>):Promise<Array<number>>;

export function TrackIDsForArtists(arg1:Array<string>):Promise<Array<number>>;

export function UnlockArtistFields(arg1:string):Promise<void>;

export function WriteArtistMetadata(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<number>;

export function WriteBulkTrackMetadata(arg1:Array<number>,arg2:backend.BulkMeta):Promise<number>;

export function WriteTrackMetadata(arg1:backend.TrackMeta):Promise<void>;
